import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ErrorState, LoadingState } from "../components/AsyncState";
import { useCaseContext } from "../context/CaseContext";
import { getDashboard } from "../services/api";
import type { DashboardData } from "../types/workspace";

export function HomePage() {
  const { caseId } = useCaseContext(); const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(false);
  const load = useCallback(() => { setError(false); getDashboard(caseId).then(setData).catch(() => setError(true)); }, [caseId]); useEffect(load, [load]);
  if (error) return <ErrorState label="Unable to load dashboard intelligence." retry={load}/>; if (!data) return <LoadingState label="Loading investigation overview..."/>;
  const metrics = [{ label: "Active cases", value: data.metrics.active_cases }, { label: "Case entities", value: data.metrics.entities }, { label: "Open alerts", value: data.metrics.open_alerts }, { label: "Anomalies", value: data.metrics.anomalies }, { label: "Documents", value: data.metrics.documents }];
  return <section className="page"><header className="page-header"><div><p className="eyebrow">Unified investigation workspace</p><h1>Project Eclipse</h1><p className="muted">VEIL-2026-001 · Synthetic demonstration investigation</p></div><div className="quick-links"><Link className="veil-button secondary" to="/cases/1">Case overview</Link><Link className="veil-button" to="/network">Explore network</Link></div></header><div className="metric-grid">{metrics.map((item) => <div className="metric" key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div><div className="veil-grid-2"><section className="veil-panel"><div className="panel-head"><h2>Priority entities</h2><Link to="/entities">View all</Link></div><div className="veil-table-wrap"><table className="veil-table"><thead><tr><th>Entity</th><th>Priority</th><th>Key signal</th><th>Data sufficiency</th></tr></thead><tbody>{data.priority_entities.map((item) => <tr key={item.entity_id}><td><Link to={`/entities/P${String(item.entity_id).padStart(3,"0")}`}>{item.name}</Link></td><td>{item.score.toFixed(0)} / 100</td><td>{item.key_signal}</td><td><span className="status-pill">{item.data_sufficiency}</span></td></tr>)}</tbody></table></div></section><section className="veil-panel"><div className="panel-head"><h2>Recent alerts</h2><Link to="/alerts">Alert center</Link></div><div className="panel-body stack-list">{data.recent_alerts.map((item) => <div className="stack-row" key={item.id}><div><span className={`status-pill ${item.severity}`}>{item.severity}</span> <Link to={`/alerts?selected=${item.id}`}>{item.title}</Link></div><small className="muted">Score {item.score.toFixed(0)} · {item.status}</small></div>)}</div></section></div><section className="veil-panel"><div className="panel-head"><h2>Anomaly overview</h2><span className="muted">Stored analytical signals over time</span></div><div className="panel-body anomaly-bars">{data.anomaly_series.length ? data.anomaly_series.slice(-18).map((item, index) => <div className="anomaly-bar" key={`${item.type}-${index}`} title={`${item.type}: ${item.score}`} style={{ height: `${Math.max(8,item.score)}%` }}><span>{item.type.split("_")[0]}</span></div>) : <p className="muted">No calculated anomaly snapshots. Run Phase 4 recalculation to populate this view.</p>}</div></section><p className="disclaimer">Analytical priority organizes review based on observed data. It is not a determination or probability of criminality.</p></section>;
}
